[versions]
min_sdk_version = "21"
target_sdk_version = "34"
compile_sdk_version = "34"

agp = "8.5.2"
androidx_recyclerview = "1.3.2"
appcompat = "1.6.1"
appintro = "5.1.0"
constraint_layout = "2.1.4"
dagger = "2.16"
detekt = "1.23.6"
junit = "4.13.2"
kotlin = "1.9.25"
materialcomponents = "1.0.0"
mockitoCore = "3.12.4"
mockitoKotlin = "2.2.0"
rxandroid2 = "2.1.1"
rxjava2 = "2.2.21"

[libraries]
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint.layout" }
androidx_recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "androidx_recyclerview" }
appintro = { module = "com.github.paolorotolo:appintro", version.ref = "appintro" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger" }
dagger_android = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
dagger_android_processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }
dagger_compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
junit = { module = "junit:junit", version.ref = "junit" }
materialcomponents = { module = "com.google.android.material:material", version.ref = "materialcomponents" }
mockito_core = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
mockito_kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
rxandroid2 = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid2" }
rxjava2 = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava2" }
detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
